/**
 * Feature extractor tests.
 *
 * Reference values were generated by the Python feature_service_universal.py
 * (the source of truth used during model training) and cross-checked manually.
 */
import { describe, it, expect } from "vitest";
import {
  djb2Hash,
  findVowels,
  buildFeaturesUniversal,
  featurise,
  EXPECTED_FEATURE_COUNT,
  FEATURE_NAMES,
} from "../src/featurise.js";

// ── djb2Hash ──────────────────────────────────────────────────────────────────
describe("djb2Hash", () => {
  it("returns 0 for empty string mod any", () => {
    // 5381 % 512 = 5381 - 10*512 = 5381 - 5120 = 261
    expect(djb2Hash("", 512)).toBe(5381 % 512);
  });

  it("matches Python for 'tet' mod 512", () => {
    // suffix_hash_3 for 'університет' (last 3 = 'тет') should be 702
    expect(djb2Hash("тет", 1024)).toBe(702);
  });

  it("is deterministic", () => {
    const a = djb2Hash("університет", 2048);
    const b = djb2Hash("університет", 2048);
    expect(a).toBe(b);
  });
});

// ── findVowels ────────────────────────────────────────────────────────────────
describe("findVowels", () => {
  it("finds 5 vowels in університет", () => {
    expect(findVowels("університет")).toHaveLength(5);
  });

  it("returns correct positions", () => {
    // у-н-і-в-е-р-с-и-т-е-т
    // 0 1 2 3 4 5 6 7 8 9 10
    expect(findVowels("університет")).toEqual([0, 2, 4, 7, 9]);
  });

  it("returns empty for consonant-only string", () => {
    expect(findVowels("бтл")).toEqual([]);
  });
});

// ── buildFeaturesUniversal ────────────────────────────────────────────────────
describe("buildFeaturesUniversal", () => {
  it("returns exactly 132 features", () => {
    const feat = buildFeaturesUniversal("університет", "NOUN");
    expect(Object.keys(feat)).toHaveLength(EXPECTED_FEATURE_COUNT);
  });

  describe("університет (NOUN)", () => {
    const feat = buildFeaturesUniversal("університет", "NOUN");

    it("word_len = 11", () => expect(feat["word_len"]).toBe(11));
    it("vowel_count = 5", () => expect(feat["vowel_count"]).toBe(5));
    it("suffix_hash_3 = 702", () => expect(feat["suffix_hash_3"]).toBe(702));
    it("syllable_count_u = 5", () => expect(feat["syllable_count_u"]).toBe(5));
    it("dist_from_end_v_last_u = 1", () =>
      expect(feat["dist_from_end_v_last_u"]).toBe(1));
    it("v_last_char_u = 1", () => expect(feat["v_last_char_u"]).toBe(1)); // 'е' → index 1
    it("has_vy_prefix_u = 0", () => expect(feat["has_vy_prefix_u"]).toBe(0));
    it("has_verb_yty_u = 0", () => expect(feat["has_verb_yty_u"]).toBe(0));
    it("ending_hash_4_u = 1174", () =>
      expect(feat["ending_hash_4_u"]).toBe(1174));
    it("pos_int = 0", () => expect(feat["pos_int"]).toBe(0)); // NOUN

    it("morph_case defaults to -1", () => expect(feat["morph_case"]).toBe(-1));
    it("morph_n_features defaults to 0", () =>
      expect(feat["morph_n_features"]).toBe(0));
  });

  describe("любити (VERB)", () => {
    const feat = buildFeaturesUniversal("любити", "VERB");

    it("word_len = 6", () => expect(feat["word_len"]).toBe(6));
    it("vowel_count = 3", () => expect(feat["vowel_count"]).toBe(3));
    it("syllable_count_u = 3", () => expect(feat["syllable_count_u"]).toBe(3));
    it("has_verb_yty_u = 1", () => expect(feat["has_verb_yty_u"]).toBe(1));
    it("dist_from_end_v_last_u = 0", () =>
      expect(feat["dist_from_end_v_last_u"]).toBe(0));
    it("pos_int = 1", () => expect(feat["pos_int"]).toBe(1)); // VERB
    it("ending_hash_4_u = 1288", () =>
      expect(feat["ending_hash_4_u"]).toBe(1288));
  });

  describe("красивий (ADJ)", () => {
    const feat = buildFeaturesUniversal("красивий", "ADJ");

    it("word_len = 8", () => expect(feat["word_len"]).toBe(8));
    it("vowel_count = 3", () => expect(feat["vowel_count"]).toBe(3));
    it("pos_int = 2", () => expect(feat["pos_int"]).toBe(2)); // ADJ
    it("ending_hash_4_u = 224", () =>
      expect(feat["ending_hash_4_u"]).toBe(224));
  });

  describe("виходити (VERB)", () => {
    const feat = buildFeaturesUniversal("виходити", "VERB");

    it("word_len = 8", () => expect(feat["word_len"]).toBe(8));
    it("vowel_count = 4", () => expect(feat["vowel_count"]).toBe(4));
    it("syllable_count_u = 4", () => expect(feat["syllable_count_u"]).toBe(4));
    it("has_vy_prefix_u = 1", () => expect(feat["has_vy_prefix_u"]).toBe(1));
    it("has_verb_yty_u = 1", () => expect(feat["has_verb_yty_u"]).toBe(1));
    it("ending_hash_4_u = 2603", () =>
      expect(feat["ending_hash_4_u"]).toBe(2603));
  });

  describe("edge cases", () => {
    it("unknown POS → pos_int = 12", () => {
      const feat = buildFeaturesUniversal("слово", "ZZZZ");
      expect(feat["pos_int"]).toBe(12);
    });

    it("word with apostrophe → has_apostrophe = 1", () => {
      const feat = buildFeaturesUniversal("м'яч", "NOUN");
      expect(feat["has_apostrophe"]).toBe(1);
    });

    it("single vowel word → vowel_count = 1, no penult", () => {
      const feat = buildFeaturesUniversal("і", "CONJ");
      expect(feat["vowel_count"]).toBe(1);
      expect(feat["dist_from_end_v_pen_u"]).toBe(-1);
    });
  });
});

// ── featurise (Float32Array) ──────────────────────────────────────────────────
describe("featurise", () => {
  it("returns Float32Array of length 132", () => {
    const arr = featurise("університет", "NOUN");
    expect(arr).toBeInstanceOf(Float32Array);
    expect(arr.length).toBe(EXPECTED_FEATURE_COUNT);
  });

  it("first element matches word_len", () => {
    const arr = featurise("університет", "NOUN");
    expect(arr[0]).toBe(11); // word_len
  });

  it("feature order matches FEATURE_NAMES", () => {
    const feat = buildFeaturesUniversal("університет", "NOUN");
    const arr = featurise("університет", "NOUN");
    for (let i = 0; i < FEATURE_NAMES.length; i++) {
      expect(arr[i]).toBeCloseTo(feat[FEATURE_NAMES[i]] ?? 0, 5);
    }
  });
});
