/**
 * Public types exported by ua-word-stress.
 */

/** Result of a full stress lookup. */
export interface LookupResult {
  /**
   * All stressed vowel indices (0-based among Ukrainian vowels in the word),
   * in order from most common to least common.
   *
   * - Length 1 → unambiguous stress.
   * - Length 2 → two valid positions; see `type` for interpretation.
   *
   * @example
   * // 'університет': vowels у(0) і(1) е(2) и(3) е(4) → stresses=[4]
   * // 'замок':       vowels а(0) о(1)               → stresses=[0, 1]
   * // 'помилка':     vowels о(0) и(1) а(2)           → stresses=[0, 1]
   */
  stresses: number[];

  /**
   * Convenience alias for `stresses[0]` — the primary (most common) stress.
   */
  stress: number;

  /**
   * Stress classification:
   *
   * - `"unique"`    — one unambiguous stress position.
   * - `"variative"` — multiple positions, all orthographically valid
   *                   simultaneously (e.g. _по́милка_ / _поми́лка_).
   *                   Any position is correct; present both or pick either.
   * - `"heteronym"` — multiple positions corresponding to different
   *                   meanings or grammatical forms
   *                   (e.g. _за́мок_ "lock" / _замо́к_ "castle";
   *                    _бло́хи_ gen.sg / _блохи́_ nom.pl).
   *                   The correct stress depends on the intended meaning/form;
   *                   context-aware disambiguation is required.
   */
  type: "unique" | "variative" | "heteronym";

  /**
   * @deprecated Use `type !== "unique"` instead.
   * Kept for backward compatibility with v1 consumers.
   */
  uncertain: boolean;
}

/**
 * Metadata from the built `.ctrie` file, populated after loading.
 * All values are derived from the binary header and the manifest.json
 * generated by `build_web_stress_db.py`.
 */
export interface TrieStats {
  /** Total number of word forms stored in the trie. */
  wordCount: number;
  /** Total number of internal trie nodes. */
  nodeCount: number;
  /** Compressed file size in bytes (the `.ctrie.gz` you serve). */
  gzSizeBytes: number;
}

/** Ukrainian vowels (lowercase). */
export type UkrainianVowel =
  | "а"
  | "е"
  | "є"
  | "и"
  | "і"
  | "ї"
  | "о"
  | "у"
  | "ю"
  | "я";
