/**
 * Public types exported by ua-stress-trie.
 */

/** Result of a full stress lookup. */
export interface LookupResult {
  /**
   * 0-based index of the stressed vowel among Ukrainian vowels in the word.
   *
   * @example
   * // 'університет' has vowels: у(0) і(1) е(2) и(3) е(4) → stress=4
   * // 'мама'        has vowels: а(0) а(1)               → stress=0
   */
  stress: number;

  /**
   * `true` when the word is a **heteronym** — it has multiple valid stress
   * positions depending on context (e.g. за́мок vs замо́к).
   *
   * When `uncertain` is `true`, consider using the Luscinia ONNX model for
   * context-aware resolution.
   */
  uncertain: boolean;
}

/**
 * Metadata from the built `.ctrie` file, populated after loading.
 * All values are derived from the binary header and the manifest.json
 * generated by `build_web_stress_db.py`.
 */
export interface TrieStats {
  /** Total number of word forms stored in the trie. */
  wordCount: number;
  /** Total number of internal trie nodes. */
  nodeCount: number;
  /** Compressed file size in bytes (the `.ctrie.gz` you serve). */
  gzSizeBytes: number;
}

/** Ukrainian vowels (lowercase). */
export type UkrainianVowel =
  | "а"
  | "е"
  | "є"
  | "и"
  | "і"
  | "ї"
  | "о"
  | "у"
  | "ю"
  | "я";
